version: '3.3'

volumes:
  my-db:
    driver: local

services:

  mysql-db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    hostname: mysql-host
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

#  stocks-api-service:
#    image: stocks-api:latest
#    container_name: stocks-api
#    build: .
#    depends_on:
#      - mysql-db
#    links:
#      - mysql-db
#    ports:
#      - '8000:8000'
#    expose:
#      - '8000'