server:
  port: 8000
spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hiberante.dialetct.MySQLSDialect
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/db
    user: user
    password: password
    table: schema_version
    locations: classpath:db/migration
    schemas: db
    defaultSchema: db
    baselineOnMigrate: true
    baselineVersion: 0

stock-properties:
  pageSize: 3