swagger: '2.0'
info:
  title: Stock Service
  description: 'This contract exposes the APIs for stock service, with the help of these API you can maintain in the database. The APIs help you fetch the list of available stocks, add a new stock also allows you to do partial update and delete a particular stock '
  version: 1.0.0



#servers:
#  - url: https://petstore.swagger.io/v2
#  - url: http:/exampl.com/v1/api

#host: petstore.swagger.io
#schemes:
#  - http
#  - https
basePath: /v1/api
paths:
  /stocks:
    get:
      tags:
        - stocks
      summary: Get a list of all Stocks
      operationId: getAllStock
      responses:
        '200':
          description: list of stocks
          schema:
            type: array
            items:
              $ref: '#/definitions/schemas/Stock'

    post:
      tags:
        - stocks
      summary: Add a new stock
      operationId: addStock
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the pet"
        required: true
        schema:
          $ref: '#/definitions/schemas/Stock'
      responses:
        '200':
          description: success
        '405':
          description: Invalid input

  /stocks/{id}:
    get:
      tags:
        - stocks
      summary: Get stock by Id
      operationId: getStockById
      parameters:
        - name: id
          in: path
          description: ID of pet to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/schemas/Stock'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found

    patch:
      tags:
        - stocks
      summary: update the price of a particular stock
      operationId: updateStockPrice
      parameters:
        - name: id
          in: path
          description: ID of stock
          required: true
          type: integer
          format: int64
        - in: "body"
          name: "body"
          description: "order placed for purchasing the pet"
          required: true
          schema:
            $ref: '#/definitions/schemas/Stock'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/schemas/Stock'
        '400':
          description: Invalid ID supplied
        '404':
          description: Stock not found

    delete:
      tags:
        - stocks
      summary: delete a particular stock by Id
      operationId: deleteStockById
      parameters:
      - name: id
        in: path
        description: ID of stock
        required: true
        type: integer
        format: int64
      responses:
        204:
          description: successful operation
#        400:
#          description: Invalid ID supplied
#          content: {}
#        404:
#          description: Stock not found
#          content: {}


definitions:
#  schemas:
  Stock:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: Apple
      currentPrice:
        $ref: '#/components/schemas/Amount'
      lastUpdate:
        type: string
        format: datetime
        example:

  Amount:
    type: object
    properties:
      price:
        type: number
        example: 10.10
      currency:
        type: string
        example: "EUR"

